### PR TITLE
Fix GH Actions PR Workflow Support for PRs from External Contributors

### LINKED ISSUE #30: Feast Spark CI does not support PRs from external contributors
Currently our CI is set up to use secrets from Github Actions. These secrets are not exposed when an external user submits a PR, meaning our CI fails.

Example: https://github.com/feast-dev/feast-spark/pull/28/checks

### PR DESCRIPTION
**Pull request by mrzzy**
**What this PR does / why we need it**:
Fix GH Actions PR Workflow Support for PRs from External Contributors:
- Move the job that require secrets (`build-push-docker-images-for-e2e-tests`) from  `pr.yml` Github Actions Workflow into `pr_secrets.yml` Workflow.
- Trigger `pr_secrets.yml` Workflow using `pull_request_target`:
     - :warning: There are some [security implications in using `pull_request_target`](https://securitylab.github.com/research/github-actions-preventing-pwn-requests)
     - One security implication is that this exposes a read/write `GITHUB_TOKEN` and all secrets to forked PRs (with `ok-to-test`).
     - Gate jobs in `pr_secrets.yml` that require secrets by checking for the `ok-to-test` label set by Prow to prevent secrets from unintentionally exposed to malicious/unreviewed forks.
     - Since the Workflow YAML used when using `pull_request_target` is from the base repository, updating Workflow YAML from a Pull Request might result in unexpected behaviour: The updated Workflow YAML from the forked repository is not the one that is run by the CI checks (for `pr-secrets.yml`) but instead one from the base repository.

**Which issue(s) this PR fixes**:

Fixes #30

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: infra/scripts/trigger-github-actions-pr-workflow.sh [hunk 1]
```diff
@@ -0,0 +1,16 @@
+# Trigger Github Actions PR Workflow by creating a workflow dispatch event via a POST request.
+# Expects environment variables to be passed:
+# PULL_PULL_SHA - pull request hea SHA.
+# GCP_PROJECT_ID - GCP Project ID to pass to the PR workflow.
+# GCP_SA_KEY - Service Account credentials in JSON format to pass to the PR workflow.
+curl -X POST \
```
Comment (woop) [inline infra/scripts/trigger-github-actions-pr-workflow.sh:6]: By the way it may be easier to use `base64` encoding when sending the JSON blob. Not sure if you are running into any transmission issues. Should be easy to unencode on the other side.

Comment (mrzzy) [reply infra/scripts/trigger-github-actions-pr-workflow.sh]: This is a good point and I did encounter issues encoding JSON as string.
However I've change the approached used completely, so this is not longer relevant.

**Comment by mrzzy** [comment]
The approach used in this PR has changed: 
- Old Approach: `/ok-to-test` comment -> Prow -> Workflow Dispatch Request with Secrets -> Workflow with Secrets.
    -  Issues with this Approach:
        - Requires a GitHub Token to authenticate with Github API to make the Workflow Dispatch Request.
        - Added complexity having to deal with the GItHub API.
        - Checks do not register on Pull Request Details, Adding Checks manually requires more Github API tweaking (possibly JavaScript).
- New Approach: `/ok-to-test` comment -> Prow labels `ok-to-test` -> Gated CI Workflow with Secrets runs (`pr-secrets.yml`).
    - Issues with this Approach:
        - One security implication is that this exposes a read/write GITHUB_TOKEN and all secrets to forked PRs (with `ok-to-test` label).
        - Since the Workflow YAML used when using `pull_request_target` is from the base repository, updating Workflow YAML from a Pull Request might result in unexpected behaviour: The updated Workflow YAML is not the one that is run by the CI checks.

File: .github/workflows/pr_secrets.yml [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+      matrix:
+        component: [jobservice, spark]
+    env:
+      GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
+      REGISTRY: gcr.io/kf-feast
+      MAVEN_CACHE: gs://feast-templocation-kf-feast/.m2.2020-08-19.tar
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          # pull_request_target runs the workflow in the context of the base repo
```
Comment (woop) [inline .github/workflows/pr_secrets.yml:28]: Does this mean a PR won't have test details showing up in the PR itself?

Comment (mrzzy) [reply .github/workflows/pr_secrets.yml:28]: The test details/checks for the PR does show on the PR [from my own testing repo](https://github.com/mrzzy/ci-poc/pull/2/checks?check_run_id=2027906079).

However, since `pull_request_target` retrieves its Workflow YAML from the base repository. But `pr_secrets.yml` does not yet exist in the base repository which could be why we don't see the check for this PR (hence merging is tricky).

Comment (woop) [reply .github/workflows/pr_secrets.yml:28]: You can just push the workflow into this repo for now. As long as you delete it when you are done testing (or it doesnt break the test suite for everyone)

Comment (mrzzy) [reply .github/workflows/pr_secrets.yml:28]: I'm going to play it safe by creating a new PR #37 using a normal instead of forked branch so that we can ensure that this not break the existing the CI.

**Comment by mrzzy** [comment]
Reopened as PR #37
